#!/usr/bin/env bash
#SBATCH --partition=research
#SBATCH --cpus-per-task=16
#SBATCH --gres=gpu:v100:4
#SBATCH --time=100:0:0
#SBATCH --exclude=euler17
#SBATCH -o slurm.%j.%N.out # STDOUT
#SBATCH -e slurm.%j.%N.err # STDERR
#SBATCH --job-name=adalai


module load anaconda/mini/4.9.2
#module load nvidia/cuda/11.3.1

#module load anaconda/3
bootstrap_conda
#conda create -y -n minienv python=3

conda activate detectron_fcos

#conda install -y pytorch torchvision cudatoolkit=10.2 -c pytorch
#conda install -y tensorboard pillow
#pip install opencv-python
#pip install matplotlib pandas Pillow scikit-learn scipy seaborn tensorboardX

which python
hostname
echo $CUDA_VISIBLE_DEVICES
nvidia-smi
top -b -d1 -n1 | grep -i "%Cpu" #This will show cpu utilization at the start of the script

export DETECTRON2_DATASETS=/srv/home/bhavya/datasets/coco17_distorted/shot_noise/5
#export DETECTRON2_DATASETS=/srv/home/bhavya/datasets/
OMP_NUM_THREADS=1 python tools/train_net.py --config-file configs/FCOS-Detection/R_50_1x.yaml --num-gpus 4 --dist-url tcp://127.0.0.1:11246 OUTPUT_DIR training_dir/fcos_R_50_1x_shot5_repeat SOLVER.CHECKPOINT_PERIOD 30000
#OMP_NUM_THREADS=1 python tools/train_net.py --config-file configs/FCOS-Detection/R_50_1x.yaml  --eval-only --num-gpus 1 OUTPUT_DIR test MODEL.WEIGHTS training_dir/fcos_R_50_1x/model_final.pth

#python tools/visualize_data.py --config-file configs/FCOS-Detection/R_50_1x.yaml --source annotation --output-dir dir2/ 

#python tools/visualize_json_results.py --input testing/inference/coco_instances_results.json --output dir/ --dataset coco_2017_val
#export DETECTRON2_DATASETS=/srv/home/bhavya/datasets/coco17_distorted/motion_shot/0
#python tools/visualize_json_results.py --input testing0/inference/coco_instances_results.json --output dir0/ --dataset coco_2017_val
#export DETECTRON2_DATASETS=/srv/home/bhavya/datasets/coco17_distorted/motion_shot/1
#python tools/visualize_json_results.py --input testing1/inference/coco_instances_results.json --output dir1/ --dataset coco_2017_val
#export DETECTRON2_DATASETS=/srv/home/bhavya/datasets/coco17_distorted/motion_shot/2
#python tools/visualize_json_results.py --input testing2/inference/coco_instances_results.json --output dir2/ --dataset coco_2017_val
#export DETECTRON2_DATASETS=/srv/home/bhavya/datasets/coco17_distorted/motion_shot/3
#python tools/visualize_json_results.py --input testing3/inference/coco_instances_results.json --output dir3/ --dataset coco_2017_val
#export DETECTRON2_DATASETS=/srv/home/bhavya/datasets/coco17_distorted/motion_shot/4
#python tools/visualize_json_results.py --input testing4/inference/coco_instances_results.json --output dir4/ --dataset coco_2017_val
#export DETECTRON2_DATASETS=/srv/home/bhavya/datasets/coco17_distorted/motion_shot/5
#python tools/visualize_json_results.py --input testing5/inference/coco_instances_results.json --output dir5/ --dataset coco_2017_val

#python demo/demo.py --config-file configs/FCOS-Detection/R_50_1x.yaml --output generated/output  --input generated/0.png generated/1.png generated/2.png generated/3.png generated/4.png generated/5.png generated/6.png generated/7.png generated/8.png generated/9.png --opts MODEL.WEIGHTS training_dir/fcos_R_50_1x/model_final.pth


#OMP_NUM_THREADS=1 python tools/train_net.py --config-file configs/FCOS-Detection/city_R_50_1x.yaml --num-gpus 4 --dist-url tcp://127.0.0.1:12146 OUTPUT_DIR training_dir/city/R_50_1x_nochoice_lr005 SOLVER.CHECKPOINT_PERIOD 30000
